INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('MALWARE');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('VIRUS');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('GUSANOS');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('TROYANOS');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('SPYWARE');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('ADWARE');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('RANSOMWARE');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('DOXING');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('PHISHING');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('WHALING');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('MALWARE');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('VIRUS');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('GUSANOS');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('TROYANOS');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('SPYWARE');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('ADWARE');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('RANSOMWARE');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('DOXING');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('PHISHING');

INSERT INTO TIPO_ATAQUES (NOMBRE) VALUES ('WHALING');

INSERT INTO TIPO_PUERTO (ID_TIPO_PUERTO, NOMBRE) VALUES ('T', 'TCP');

INSERT INTO TIPO_PUERTO (ID_TIPO_PUERTO, NOMBRE) VALUES ('U', 'UDP');

INSERT INTO VULNERABILIDAD (ID_VULNERABILIDAD, DESCRPCION, IP_V4) VALUES ('CRITICO', 'EL COMANDO DROPBEARCONVERT EN DROPBEAR SSH, PERMITE A LOS ATACANTES EJECUTAR CóDIGO ARBITRARIO A TRAVéS DE UN ARCHIVO DE CLAVE OPENSSH DISEñADO.', '62.223.168.80');

INSERT INTO VULNERABILIDAD (ID_VULNERABILIDAD, DESCRPCION, IP_V4) VALUES ('ALTO', 'UNA FUNCIóN DESCONOCIDA DEL COMPONENTE DBCLIENT ES AFECTADA POR ESTA VULNERABILIDAD', '22.203.40.102');

INSERT INTO VULNERABILIDAD (ID_VULNERABILIDAD, DESCRPCION, IP_V4) VALUES ('MEDIO ', 'ALGUNAS FUNCIONES DESCONOCIDAS DEL COMPONENTE DBCLIENT/SERVER ESTáN AFECTADAS', '190.10.52.40');

INSERT INTO VULNERABILIDAD (ID_VULNERABILIDAD, DESCRPCION, IP_V4) VALUES ('BAJO', 'PERMITE QUE UN ATACANTE REMOTO DETERMINE QUé DOMINIOS SE HAN RESUELTO RECIENTEMENTE A TRAVéS DE ESTE SERVIDOR DE NOMBRES Y, POR LO TANTO, QUé HOSTS SE HAN VISITADO RECIENTEMENTE.', '100.194.86.212');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO453', '255.129.112.237');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO454', '196.113.248.155');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO455', '114.164.210.101');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO456', '2.126.254.194');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO457', '87.89.90.73');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO458', '45.48.155.26');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO459', '48.89.64.115');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO460', '152.141.143.86');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO461', '200.240.27.236');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO462', '94.157.136.239');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO463', '71.28.127.74');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO464', '22.246.175.228');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO465', '23.78.27.156');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO466', '91.81.233.140');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO467', '109.180.71.72');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO468', '131.86.16.201');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO469', '106.251.227.227');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO470', '64.176.235.172');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO471', '223.245.159.192');

INSERT INTO SERVIDORES (NOMBRE, IP) VALUES ('EQUIPO472', '42.244.111.95');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('ESCRITORIO REMOTO');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('SECURE SHELL');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('INTERNET SMALL COMPUTER SYSTEM INTERFACE');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('ELASTIC FILE SYSTEM');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('TRASPORTE DE AUDIO Y VIDEO');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('WINDOWS IMAGE ACQUISITION');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('WINDOWS MANAGEMENT INSTRUMENTATION');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('NEAR FIELD COMMUNICATION');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('SERVICIO AISLMINETO DE CALVES');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('SERVICIO DE RED');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('IDENTIFICADOR DE INTERFACES');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('CAPTURA MENSAJES AGENTES LOCALES');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('ALMACENA NOMBRES DE DOMINIOS');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('TRADUCCION DE DIRECCIONES DE RED');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('INTERACTURA CON LOS SERVICIO QUE SE EJECUTAN EN EL HOST');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('SERVER MESSAGE BLOCK,');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('CONTADOR DE RENDIMIENTO');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('PRPORCIONA CONPATIBILIDAD CON INFRAESTRUCTURA');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('ENRUTA MENSAJES');

INSERT INTO SERVICIOS (NOMBRE) VALUES ('SYNAPTICS FP POLICY SERVICE');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('CB-17-E9-ED-4C-7B', 'EQUIPO1', 'YáO', 'WINDOWS', '62.223.168.80');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('97-E5-D9-B7-26-73', 'EQUIPO2', 'YóU', 'MAC OS', '22.203.40.102');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('59-CA-4A-3C-94-15', 'EQUIPO3', 'DANIèLE', 'UNIX', '190.10.52.40');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('67-70-54-CF-62-67', 'EQUIPO4', 'AMéLIE', 'SOLARIS', '100.194.86.212');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('BC-3B-BF-CD-D6-87', 'EQUIPO5', 'Kù', 'FREEBSD', '34.117.112.57');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('EB-0E-F9-CD-52-0E', 'EQUIPO6', 'VéRANE', 'OPENBSD', '188.88.105.2');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('17-35-62-26-D8-AE', 'EQUIPO7', 'MYLèNE', 'WINDOWS', '109.89.77.4');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('E6-51-93-6B-C9-F3', 'EQUIPO8', 'MAïLIS', 'MAC OS', '139.83.34.116');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('01-6D-3D-88-30-34', 'EQUIPO9', 'VéRANE', 'UNIX', '125.14.62.135');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('A3-20-6F-A5-82-55', 'EQUIPO10', 'BöRJE', 'SOLARIS', '151.191.41.135');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('41-AE-D1-F7-76-83', 'EQUIPO11', 'MéLANIE', 'FREEBSD', '183.37.144.44');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('6A-DE-DC-26-BA-8D', 'EQUIPO12', 'Jú', 'OPENBSD', '251.147.95.98');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('BB-16-38-1A-42-58', 'EQUIPO13', 'SOLèNE', 'WINDOWS', '253.128.79.183');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('31-A5-E4-3D-88-5C', 'EQUIPO14', 'MéGANE', 'MAC OS', '132.111.166.98');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('37-8C-6E-3C-7A-33', 'EQUIPO15', 'PéLAGIE', 'UNIX', '245.172.92.13');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('47-44-36-C2-FA-B8', 'EQUIPO16', 'LèI', 'SOLARIS', '244.42.225.43');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('1F-70-C1-16-37-2B', 'EQUIPO17', 'GéRALD', 'FREEBSD', '42.217.87.167');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('C3-8C-73-1C-35-6A', 'EQUIPO18', 'YáO', 'OPENBSD', '69.120.170.49');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('8B-BC-E2-77-7B-CE', 'EQUIPO19', 'MAïLYS', 'WINDOWS', '149.86.155.177');

INSERT INTO EQUIPOS (ID_EQUIPOS, NOMBRE, USUARIO, SISTEMA_OPERATIVO, IP_V4) VALUES ('C5-1A-EB-9E-DB-EF', 'EQUIPO20', 'GAëLLE', 'MAC OS', '109.65.62.240');

INSERT INTO ACTULIZACION (ID_ATUALIZACION, ID_EQUIPOS, NOMBRE) VALUES ('ACT', 'A3-20-6F-A5-82-55', 'ACTUALIZADO');

INSERT INTO ACTULIZACION (ID_ATUALIZACION, ID_EQUIPOS, NOMBRE) VALUES ('DES', '31-A5-E4-3D-88-5C', 'DESACTUALIZADO');

INSERT INTO ESTADO_PUERTO (ID_ESTADO_PUERTO, NOMBRE) VALUES ('CR', 'CERRADO');

INSERT INTO ESTADO_PUERTO (ID_ESTADO_PUERTO, NOMBRE) VALUES ('AB', 'ABIERTO');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (1, 'TCPMUX	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (5, 'RJE	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (7, 'ECHO	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (9, 'DISCARD	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (11, 'SYSTAT	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (13, 'DAYTIME	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (17, 'QOTD	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (18, 'MSP	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (19, 'CHARGEN	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (20, 'FTPS-DATA	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (21, 'FTP-CONTROL	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (22, 'SSH	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (23, 'TELNET	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (25, 'SMTP	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (37, 'TIME	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (39, 'RLP	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (42, 'NAMESERVER	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (43, 'NICKNAME	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (49, 'TACACS	TCP');

INSERT INTO PUERTOS (ID_PUERTOS, NOMBRE) VALUES (50, 'RE-MAIL-CK	TCP');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('IS', 'INGENIERíA SOCIAL');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('CM', 'COLABORADORES MALINTENCIONADOS');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('FSI', 'FALLAS DE SEGURIDAD EN LOS SISTEMAS INFORMáTICOS');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('PDC', 'PROPAGACIóN DE DATOS CONFIDENCIALES');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('EHD', 'EXTRAVíO O HURTO DE DISPOSITIVOS ELECTRóNICOS');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('PCP', 'POCO CONTROL POR PARTE DE TERCEROS');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('DS', 'DENEGACION DE SIRVICIOS');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('SD', 'SECUESTRO DE DATOS');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('ISQ', 'INYECCIÓN SQL');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('XSC', 'XSS O CROSS SITE SCRIPTING');

INSERT INTO ATAQUES (ID_ATAQUES, NOMBRE) VALUES ('WCB', 'WHALING O "CAZA DE BALLENAS"');

INSERT INTO APLICACIONES (ID_APLICACIONES, NOMBRE) VALUES ('#1', 'APLICACION CONTABLE');

INSERT INTO APLICACIONES (ID_APLICACIONES, NOMBRE) VALUES ('#2', 'APLICACIONE TELEFONIA');

INSERT INTO APLICACIONES (ID_APLICACIONES, NOMBRE) VALUES ('#3', 'APLICACION GESTION HUMANA');

INSERT INTO APLICACIONES (ID_APLICACIONES, NOMBRE) VALUES ('#4', 'APLICACION DE CAMARA SEGURIDA');

INSERT INTO APLICACIONES (ID_APLICACIONES, NOMBRE) VALUES ('#5', 'INTRANET');

INSERT INTO APLICACIONES (ID_APLICACIONES, NOMBRE) VALUES ('#6', 'PAGINA WEB');

INSERT INTO APLICACIONES (ID_APLICACIONES, NOMBRE) VALUES ('#7', 'APLICACION DE INVENTARIOS');

INSERT INTO ANTIVIRUS (ID_ANTIVIRUS, ID_EQUIPOS, NOMBRE, PARCHES_SEGURIDAD) VALUES ('ACT1234', '01-6D-3D-88-30-34', 'ACTIVE', '1903 (19H1)');

INSERT INTO ANTIVIRUS (ID_ANTIVIRUS, ID_EQUIPOS, NOMBRE, PARCHES_SEGURIDAD) VALUES ('DES4321', 'CB-17-E9-ED-4C-7B', 'DESACTIVE', '1809 (RS5)');

INSERT INTO ANTIVIRUS (ID_ANTIVIRUS, ID_EQUIPOS, NOMBRE, PARCHES_SEGURIDAD) VALUES ('NO INS654', '6A-DE-DC-26-BA-8D', 'NO INSTALL', '1803 (RS4)');

INSERT INTO ANTIVIRUS (ID_ANTIVIRUS, ID_EQUIPOS, NOMBRE, PARCHES_SEGURIDAD) VALUES ('EJEC13454', '97-E5-D9-B7-26-73', 'EJECUCION', '1709 (RS3)');

INSERT INTO ANTIVIRUS (ID_ANTIVIRUS, ID_EQUIPOS, NOMBRE, PARCHES_SEGURIDAD) VALUES ('DESAC54566', '97-E5-D9-B7-26-73', 'DESACTUALIZADA', '1703 (RS2)');

